### ISSUE TITLE
does not work with vue 3.2

### ISSUE THREAD

**Issue by borismarn** [announcekitapp/announcekit-vue#24]
I have trouble making it work with Vue we are using in the company.

Minimal reproduction is here with hello-world where announce kit lib is added:

https://github.com/IReallyNeedANick/announce-kit-fail

While the previous version works:
https://codesandbox.io/p/sandbox/announcekit-vue20-demo-jcfjf?file=%2Fsrc%2FApp.vue%3A15%2C15

**Comment by eslamelkholy** [comment]
Hi @IReallyNeedANick, thanks for reaching out. 

It looks like you might be using an older version of the AnnounceKit package.
I couldn't find "announcekit-vue": "3.1.0" in the repository you mentioned, so it seems it might not have been installed, as it's not in the package.json file.

We have a demo project for Vue 3 in our documentation that you can check out: [Vue 3 Demo](https://codesandbox.io/p/sandbox/announcekit-vue3-4pvwjv). In this demo, we're using Vue version 3.2 and AnnounceKit version 3.

`"dependencies": {
    "announcekit-vue": "3.1.0",
    "vue": "3.2.45"
  },`

Could you please take a look and let me know if that helps?
